# Generated by Django 4.2.4 on 2023-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietcategory',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dietcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
